### ISSUE TITLE
Revisão do README.md

### ISSUE THREAD

**Issue by danieljoppi** [mateusdeveloper/SystemMonitorMachine#1]
Teria como adicionar no README.md os requisitos para executar o teu projeto, por exemplo:
- programas instalados e as suas versões?
- o que preciso executar para rodar?
- se existeir uma interface, onde eu posso acessa-la?
- se for aplicativo console, quais comandos eu tenho que executar?

**Comment by mateusdeveloper** [comment]
Descrevi no README as informações solicitadas, estou a disposição para quaisquer dúvidas.
